### ISSUE TITLE
`secureworkload_scope` should allow for complex query

### ISSUE THREAD

**Issue by jakauppila** [CiscoDevNet/terraform-provider-secureworkload#20]
The Secure Workload UI allows the user to define a complex query when defining a scope, the Terraform resource should allow the same capability. Today, it appears restricted to a single, basic query.

**Describe the solution you'd like**
Possibly a field like `query` on `secureworkload_filter`, though it's unclear to me how to structure an `and/or/not/()` of the query within that field.

https://registry.terraform.io/providers/CiscoDevNet/secureworkload/latest/docs/resources/filter#query

Clones: https://github.com/CiscoDevNet/terraform-provider-tetration/issues/5

**Comment by kadadhic** [comment]
Thanks for raising the issue, taking a look into this. 

Will keep you posted.

**Comment by kadadhic** [comment]
Complex queries are now supported with the v1.6.0 release.
https://registry.terraform.io/providers/CiscoDevNet/secureworkload/latest/docs/resources/scope
Thanks
