### ISSUE TITLE
`secureworkload_scope` should allow defining scope type

### ISSUE THREAD

**Issue by jakauppila** [CiscoDevNet/terraform-provider-secureworkload#21]
The Cisco Secure Workload UI allows the user to define a scope "type", the Terraform resource should allow this as well.

![image](https://github.com/CiscoDevNet/terraform-provider-secureworkload/assets/4100127/d2654650-d0a4-4a6a-b94e-d715961a653e)

**Comment by kadadhic** [comment]
Fixed in the v1.6.0 release.  Look for the field "sub_type"
https://registry.terraform.io/providers/CiscoDevNet/secureworkload/latest/docs/resources/scope
Thanks
