### ISSUE TITLE
`secureworkload_scope` should not require query definition

### ISSUE THREAD

**Issue by jakauppila** [CiscoDevNet/terraform-provider-secureworkload#23]
The Secure Workload UI allows the user to omit a query when defining a scope, the Terraform resource should allow the same capability.

I'd assume this would be done when defining a scope strictly for organization purposes.

**Comment by kadadhic** [comment]
Thanks for bringing this to our attention. We are working on it.

**Comment by kadadhic** [comment]
Fixed in the v1.6.0 release. 
Check:  https://registry.terraform.io/providers/CiscoDevNet/secureworkload/latest/docs/resources/scope
Thanks
